name: Build

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup WebView2
        shell: pwsh
        run: |
          if ("${{ matrix.platform }}" -match 'windows') {
            Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe"
            Start-Process -FilePath "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" -ArgumentList "/silent", "/install" -Wait
          } else {
            echo "Skipping WebView2 installation"
          }

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm run build

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_JOBS: 2
        with:
          tagName: ${{ github.event.release.tag_name }}
          releaseName: 'KeyBoard ${{ github.event.release.tag_name }}'
          releaseBody: ${{ github.event.release.body }}
          releaseDraft: false
          prerelease: ${{ github.event.release.prerelease }}
          args: ${{ matrix.args }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WebKeyBoard-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/
            src-tauri/target/release/*.exe
            src-tauri/target/release/*.msi
          if-no-files-found: warn
